services:
  - type: web
    name: newsai
    runtime: python
    region: singapore  # Deploy to Singapore region
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    disk:
      name: newsai-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: CRON_AUTH_TOKEN
        generateValue: true
    autoDeploy: true

  - type: cron
    name: newsai-daily-digest
    runtime: python
    region: singapore  # Deploy to Singapore region
    schedule: "0 3 * * *"  # Daily at 3 AM UTC (7 AM UAE time)
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python -c "
      import os
      import requests
      from datetime import datetime
      
      render_url = os.environ.get('RENDER_EXTERNAL_URL')
      if not render_url:
          print('ERROR: RENDER_EXTERNAL_URL not set')
          exit(1)
      
      # Add https:// if not present
      app_url = f'https://{render_url}' if not render_url.startswith('http') else render_url
      token = os.environ.get('CRON_AUTH_TOKEN')
      
      is_monday = datetime.now().weekday() == 0
      digest_type = 'Monday (News + Stocks)' if is_monday else 'Daily News'
      print(f'Triggering {digest_type} for {app_url}...')
      
      # Single endpoint handles both daily news and Monday stocks
      response = requests.post(
          f'{app_url}/api/trigger/daily-digest',
          headers={'X-Auth-Token': token}
      )
      
      print(f'{digest_type} digest trigger: {response.status_code}')
      
      if response.status_code == 200:
          print(response.json())
      else:
          print(f'Error: {response.text}')
      "
    envVars:
      - key: CRON_AUTH_TOKEN
        fromService:
          type: web
          name: newsai
          envVarKey: CRON_AUTH_TOKEN
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: newsai
          property: host