# Render configuration for NewsAI Daily Email
services:
  - type: cron
    name: newsai-daily-email
    runtime: python3
    schedule: "0 2 * * *"  # Run at 2:00 AM UTC = 6:00 AM UAE time (UTC+4)
    buildCommand: pip install -r requirements.txt
    startCommand: python send_email.py
    
    envVars:
      # API Keys (set these in Render dashboard)
      - key: APP_PSWD
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: NEWS_IO_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      
      # Email Configuration
      - key: FROM_EMAIL
        value: daily.multiply.news@gmail.com
      - key: TO_EMAIL
        value: atmh2002@gmail.com
      
      # Model Configuration
      - key: OPENAI_MODEL
        value: gpt-5
      - key: PERPLEXITY_MODEL
        value: sonar-pro
      - key: GEMINI_MODEL
        value: gemini-2.5-pro
      
      # Feature Flags
      - key: ENABLE_OPENAI
        value: true
      - key: ENABLE_PERPLEXITY
        value: true
      - key: ENABLE_GEMINI
        value: true
      
      # Test Mode
      - key: TEST_MODE
        value: false